language: python

script:
  - test [ "${TRAVIS_JOB_NUMBER}" =~ \.1$ ] && BUILD_RELEASE="TRUE" || true
  - test -n $BUILD_RELEASE && bash push_to_coveralls.sh

deploy:
  provider: releases
  api_key: ${TRAVIS_TEST_RELEASE}
  file: 
    - push_to_coveralls.sh
    - 0.0.1-test.tar.gz
    - 0.0.1-test.zip
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
