language: python

script:
  - if [[ "${TRAVIS_JOB_NUMBER}" =~ \.1$ ]]; then IS_BUILD_RELEASE_JOB=true; fi
  - if [ -z ${IS_BUILD_RELEASE_JOB+x} ]; then `push_to_coveralls.sh`; fi

deploy:
  provider: releases
  api_key: ${TRAVIS_TEST_RELEASE}
  file: 
    - push_to_coveralls.sh
    - 0.0.1-test.tar.gz
    - 0.0.1-test.zip
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
